######################################################################
#Python Script Generated by Algorithm History Display 
######################################################################
LoadEventPreNeXus(EventFilename="/home/2zr/Mantid/Test/Data/sns_event_prenexus/CNCS_7850_neutron_event.dat",PadEmptyPixels="1",OutputWorkspace="cncs")
ConvertUnits(InputWorkspace="cncs",OutputWorkspace="cncsET",Target="DeltaE",EMode="Direct",EFixed="3")
ConvertUnits(InputWorkspace="cncsET",OutputWorkspace="cncsW",Target="Wavelength",EMode="Direct",EFixed="3")
