######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################

datawslist = []
monitorwslist = []
binpars = '5,0.1,150'

# reduce single Spice data set
for scanid in ['0001', '0002', '0003']: 
    LoadSpiceAscii(Filename='/home/wzz/Projects/MantidTests/Tickets/10929_Reduce_HB2A/verification_test/HB2A_exp0231_scan%s.dat' % (scanid), 
            DateAndTimeLog='date,MM/DD/YYYY,time,HH:MM:SS AM', 
            OutputWorkspace='HB2A_exp0231_scan%s_DataTable' % (scanid), 
            RunInfoWorkspace='HB2A_exp0231_scan%s_Log' % (scanid))
    
    ConvertSpiceDataToRealSpace(InputWorkspace='HB2A_exp0231_scan%s_DataTable'%(scanid), 
            RunInfoWorkspace='HB2A_exp0231_scan%s_Log' % (scanid), 
            OutputWorkspace='HB2A_exp0231_scan%s_DataMD' % (scanid), 
            OutputMonitorWorkspace='HB2A_exp0231_scan%s_MonitorMD' % (scanid))

    dataws = mtd["HB2A_exp0231_scan%s_DataMD"%(scanid)]
    datawslist.append(dataws)

    monitorws = mtd["HB2A_exp0231_scan%s_MonitorMD"%(scanid)]
    monitorwslist.append(monitorws)

    ConvertCWPDMDToSpectra(InputWorkspace='HB2A_exp0231_scan%s_DataMD' % (scanid), 
            InputMonitorWorkspace='HB2A_exp0231_scan%s_MonitorMD'%(scanid), 
            BinningParams=binpars, 
            OutputWorkspace='TwoTheta_scan%s'%(scanid), 
            NeutronWaveLength=2.4100000000000001)

# Merge 3 scans and reduce
mergedataws = datawslist[0] + datawslist[1]
for i in xrange(2, len(datawslist)):
    mergedataws += datawslist[i]
            
# Merge 3 scans and reduce
mergemonitorws = monitorwslist[0] + monitorwslist[1]
for i in xrange(2, len(monitorwslist)):
    mergemonitorws += monitorwslist[i]
            
ConvertCWPDMDToSpectra(InputWorkspace=mergedataws,
            InputMonitorWorkspace=mergemonitorws,
            BinningParams=binpars, 
            OutputWorkspace='TwoTheta_Merged', 
            NeutronWaveLength=2.4100000000000001) 
