######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
LoadSpiceAscii(Filename='/home/wzz/Projects/MantidTests/Tickets/10929_Reduce_HB2A/verification_test/HB2A_exp0231_scan0001.dat', DateAndTimeLog='date,MM/DD/YYYY,time,HH:MM:SS AM', OutputWorkspace='HB2A_exp0231_scan0001_DataTable', RunInfoWorkspace='HB2A_exp0231_scan0001_Log')
ConvertSpiceDataToRealSpace(InputWorkspace='HB2A_exp0231_scan0001_DataTable', RunInfoWorkspace='HB2A_exp0231_scan0001_Log', OutputWorkspace='HB2A_exp0231_scan0001_DataMD', OutputMonitorWorkspace='HB2A_exp0231_scan0001_MonitorMD')
ConvertCWPDMDToSpectra(InputWorkspace='HB2A_exp0231_scan0001_DataMD', InputMonitorWorkspace='HB2A_exp0231_scan0001_MonitorMD', BinningParams='5,0.01,150', OutputWorkspace='TTheta', NeutronWaveLength=2.4100000000000001)
