######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
LoadRaw(Filename=r'/archive/ndxwish/Instrument/data/cycle_13_2/WISH00025088.raw',OutputWorkspace='25088',LoadLogFiles='0')
CropWorkspace(InputWorkspace='25088',OutputWorkspace='25088',XMin='6000',XMax='99000')
NormaliseByCurrent(InputWorkspace='25088',OutputWorkspace='25088')
LoadIsawUB(InputWorkspace='25088',Filename=r'/home/ryb18365/Desktop/LuFe2O4/ab_plane/UB_25078.mat')
ConvertToDiffractionMDWorkspace(InputWorkspace='25088',OutputWorkspace='25088_MD',OutputDimensions='HKL',LorentzCorrection='1',SplitInto='2,2,2',SplitThreshold='30')
BinMD(InputWorkspace='25088_MD',AxisAligned='0',BasisVector0='-h-h0,arb,-1,-1,0',BasisVector1='h-h0,arb,1,-1,0',BasisVector2='00l,arb,0,0,1',OutputExtents='0,1.5,-1,1,-2,2',OutputBins='100,10,80',NormalizeBasisVectors='0',OutputWorkspace='25088_MD_rebin')
BinMD(InputWorkspace='25088_MD_rebin',AxisAligned='0',BasisVector0='X,units,6.12303e-17,0,-1',BasisVector1='Y,units,1,0,0',BasisVector2='2,units,0,1,0',Translation='0.333,0,0.7',OutputExtents='0,1.7,-0.01,0.01,-0.1,0.1',OutputBins='100,1,1',OutputWorkspace='25088_MD_rebin_line')
QueryMDWorkspace(InputWorkspace='25088_MD_rebin_line',OutputWorkspace='25088_MD_rebin_line_data_list_table',LimitRows='0')
ConvertTableToMatrixWorkspace(InputWorkspace='25088_MD_rebin_line_data_list_table',OutputWorkspace='25088_int_qwe',ColumnX='2/units',ColumnY='Signal/none',ColumnE='Error/none')
