######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
CreateLeBailFitInput(ReflectionsFile=r'LaB6_bank1M.hkl',FullprofParameterFile=r'bank3test.irf',Bank='3',LatticeConstant='4.1568899999999998',InstrumentParameterWorkspace='InstrumentTable',BraggPeakParameterWorkspace='PeakTable')
