######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
FitPowderDiffPeaks(InputWorkspace='PG3_11485',
        OutputWorkspace='Bank1FittedPeaks',
        BraggPeakParameterWorkspace='BraggPeakParameterTable2',
        InstrumentParameterWorkspace='Bank1InstrumentParameterTable1',
        OutputBraggPeakParameterWorkspace='BraggPeakParameterTable2_0',
        OutputBraggPeakParameterDataWorkspace='BraggPeakParameterTable2_P',
        OutputZscoreWorkspace='BraggPeakParameterTable2_Zscore',
        MinTOF='15000',MaxTOF='49387',
        UseGivenPeakCentreTOF='0',
        MinimumPeakHeight='0.29999999999999999',
        PeaksCorrelated='1',
        MinimumHKL='12,12,12',
        RightMostPeakHKL='2,0,0',
        RightMostPeakLeftBound='46000',
        RightMostPeakRightBound='48000')
