######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
# 1. Load data
LoadAscii(Filename=r'PG3_11485-1.dat',OutputWorkspace='PG3_11485',Unit='TOF')

# 2. Create inputs for LeBailFit() to check the starting values of instrument profile
CreateLeBailFitInput(ReflectionsFile=r'LB4844b1.hkl',
        FullprofParameterFile=r'2011B_HR60b1.irf',
        LatticeConstant='4.1568899999999998',
        InstrumentParameterWorkspace='Bank1InstrumentParameterTable1',
        BraggPeakParameterWorkspace='BraggPeakParameterTable1')

# 3. Process background roughly and fit to a polynomiail
ProcessBackground(InputWorkspace='PG3_11485',
        OutputWorkspace='PG3_11485_Background',
        Options='SelectBackgroundPoints',
        LowerBound='5053',
        UpperBound='49387',
        BackgroundPoints='5243,8910,11165,12153,13731,15060,16511,17767,19650,21874,23167,24519,36000,44282,49000',NoiseTolerance='0.10000000000000001')

Fit(Function='name=Polynomial,n=6,A0=0.558765,A1=-3.367e-05,A2=-9.89997e-10,A3=2.29598e-13,A4=-1.07727e-17,A5=2.10057e-22,A6=-1.49446e-27',
        InputWorkspace='PG3_11485_Background',
        MaxIterations='1000',
        Minimizer='Levenberg-MarquardtMD',
        CreateOutput='1',
        Output='PG3_11485_Background',
        StartX='5053',
        EndX='49387')

# 4. Execute LeBailFit in pattern calculation mode
LeBailFit(InputWorkspace='PG3_11485',
        OutputWorkspace='PG3_11485_InitGuess',
        InputParameterWorkspace='Bank1InstrumentParameterTable1',
        OutputParameterWorkspace='TempTable',
        InputHKLWorkspace='BraggPeakParameterTable1',
        OutputPeaksWorkspace='BraggPeakParameterTable2',
        Function='Calculation',
        BackgroundParametersWorkspace='PG3_11485_Background_Parameters',
        PeakRadius='8',
        UseInputPeakHeights='0',
        Minimizer='Levenberg-Marquardt')
