######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
# Load and process event data
Load(Filename=r'PG3_2538_event.nxs',OutputWorkspace='PG3_2538_event')
Rebin(InputWorkspace='PG3_2538_event',OutputWorkspace='PG3_2538_event',Params='-0.0001')
ConvertUnits(InputWorkspace='PG3_2538_event',OutputWorkspace='PG3_2538_event',Target='dSpacing')

# Fit peak
FitPeak(InputWorkspace='PG3_2538_event',OutputWorkspace='peak5_model',ParameterTableWorkspace='peak5_parameters',
	WorkspaceIndex='22000',PeakFunctionType='Gaussian (Height, PeakCentre, Sigma)',PeakParameterValues='1,1.26,0.01',
	BackgroundType='Linear (A0, A1)',BackgroundParameterValues='0,0',FitWindow='1.2,1.35',PeakRange='1.25,1.28',FitBackgroundFirst='0')
