######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
LoadAscii(Filename=r'PG3_15035-3.dat',OutputWorkspace='PG3_15035-3',Unit='TOF')
ProcessBackground(InputWorkspace='PG3_15035-3',OutputWorkspace='PG3_15035-Bkgd01',Options='SelectBackgroundPoints',SelectionMode='FitGivenDataPoints',BackgroundOrder='6', 
	BackgroundPoints='10082,10591,11154,12615,13690,13715,15073,16893,17764,19628,21318,24192,35350,44212,50900,60000,69900,79000',NoiseTolerance='0.5',
	UserBackgroundWorkspace='UserObserver',OutputBackgroundParameterWorkspace='PG3_15035_BkgdParameters01')
