######################################################################
#Python Script Generated by Algorithm History Display 
######################################################################
LoadNexusProcessed(Filename="/home/dmn58364/mantidproject/default_save/irs21360_graphite002_red.nxs",OutputWorkspace='irs21360_graphite002_red')
Fit(InputWorkspace="irs21360_graphite002_red",StartX="-0.56413041694916255",EndX="0.56963302511037361",Function="name=LinearBackground,A0=0,A1=0,ties=(A0=0.00,A1=0.0);(composite=Convolution;name=Resolution,FileName=\"/home/dmn58364/mantidproject/testscripts/irs26173_graphite002_res.nxs\";name=Lorentzian,Height=29.1171,PeakCentre=-0.00181586,HWHM=0.000406624)",OutputStatus="success",OutputChi2DoF="7.6262164694127677",Output="irs21360_graphite002_red_convfit_s0")
