######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
Load(Filename=r'/SNS/MANDI/2012_2_11b_SCI/1/306/NeXus/MANDI_306_event.nxs',OutputWorkspace='MANDI_306_event',Precount='1',LoadMonitors='1')
ConvertToMD(InputWorkspace='MANDI_306_event',OutputWorkspace='MANDI_306_md',QDimensions='Q3D',dEAnalysisMode='Elastic',LorentzCorrection='1',MinValues='-5,-5,-5',MaxValues='5,5,5',SplitInto='2',SplitThreshold='50',MaxRecursionDepth='13',MinRecursionDepth='7')
FindPeaksMD(InputWorkspace='MANDI_306_md',PeakDistanceThreshold='0.056520000000000001',OutputWorkspace='MANDI_306_peaks')
FindUBUsingFFT(PeaksWorkspace='MANDI_306_peaks',MinD='50',MaxD='160',Tolerance='0.12')
IndexPeaks(PeaksWorkspace='MANDI_306_peaks',Tolerance='0.12',RoundHKLs='0')
CopySample(InputWorkspace='MANDI_306_peaks',OutputWorkspace='MANDI_306_md',CopyName='0',CopyMaterial='0',CopyEnvironment='0',CopyShape='0')
