######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
ws = mtd["NOM_Bank4_BackgroundParameters"]

LeBailFit(
        InputWorkspace='NOM_11848-4',
        OutputWorkspace='NOM_11848-4-RefineBackground',
        InputParameterWorkspace='NOM_Bank4_ProfileTable',
        OutputParameterWorkspace='Dummy1',
        InputHKLWorkspace='LaB6_BraggPeaksTable',
        OutputPeaksWorkspace='Dummy2',
        FitRegion='2390.4,18499',
        Function='RefineBackground',
        BackgroundParametersWorkspace='NOM_Bank4_BackgroundParameters',
        PeakRadius='8',
        Minimizer='BFGS',
        NumberMinimizeSteps='1000',
        MinimumPeakHeight='0.050000000000000003')
