######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
import mantid.simpleapi as api

# 1. Load data
LoadAscii(
        Filename=r'NOM_11848-4.dat',
        OutputWorkspace='NOM_11848-4',Unit='TOF')

# 2. Create inputs
CreateLeBailFitInput(
        ReflectionsFile=r'LB4853b2.hkl',
        FullprofParameterFile=r'nom_bank4.irf',
        Bank='4',
        LatticeConstant='4.1568899999999998',
        InstrumentParameterWorkspace='NOM_Bank4_ProfileTable',
        BraggPeakParameterWorkspace='LaB6_BraggPeaksTable')

# 3. Create background parameter workspace
bkgdws = api.CreateEmptyTableWorkspace(OutputWorkspace="NOM_Bank4_BackgroundParameters")
bkgdws.addColumn("str", "Name")
bkgdws.addColumn("double", "Value")
bkgdws.addRow(["A0", 0.7])
bkgdws.addRow(["A1", -7.99912e-05])
bkgdws.addRow(["A2", -2.62568e-08])
bkgdws.addRow(["A3", 6.85818e-12 ])
bkgdws.addRow(["A4", -6.2969e-16 ])
bkgdws.addRow(["A5", 2.5987e-20  ])
bkgdws.addRow(["A6", -4.04945e-25])


print bkgdws.name()

# 4. Preview
LeBailFit(InputWorkspace='NOM_11848-4',
        OutputWorkspace='NOM_11848-4_MC_20000',
        InputParameterWorkspace='NOM_Bank4_ProfileTable',
        OutputParameterWorkspace='DummyX',
        InputHKLWorkspace='LaB6_BraggPeaksTable',
        OutputPeaksWorkspace='DummyY',
        FitRegion='2390,18500',
        Function='Calculation',
        BackgroundParametersWorkspace='NOM_Bank4_BackgroundParameters',
        PeakRadius='8',
        UseInputPeakHeights='0')
