######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
LoadSQW(Filename=r'fe_demo_30.sqw',OutputWorkspace='ws',OutputFilename=r'C:/Users/spu92482/Desktop/x2.nxs')
BinMD(InputWorkspace='ws',AlignedDimX='Q_\zeta, -1, 1, 100',AlignedDimY='Q_\xi, -6, 6, 100',AlignedDimZ='Q_\eta, -6, 6, 100',AlignedDimT='E, 0, 150, 1',OutputWorkspace='x')
