######################################################################
#Python Script Generated by Algorithm History Display 
######################################################################
LoadRaw(Filename="/home/dmn58364/Mantid/trunk/Test/Data/HRP39191.RAW",OutputWorkspace="HRP39191")
Gaussian1D(InputWorkspace="HRP39191",WorkspaceIndex="2",StartX="99800",EndX="100200",BG0="2.1083303236622837",Height="32.038502883146897",PeakCentre="100018.1156696059",Sigma="11.610612809513094",Fix="BG1",OutputStatus="success",OutputChi2DoF="1.0414024717528494",Output="out")
