######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
LoadSpiceAscii(Filename='10622_HB2A/HB2A_exp0231_scan0001.dat', OutputWorkspace='datatable', RunInfoWorkspace='inforws')
ConvertSpiceDataToRealSpace(InputWorkspace='datatable', RunInfoWorkspace='inforws', OutputWorkspace='HB2A_exp0231_scan0001_DataMD', OutputMonitorWorkspace='HB2A_exp0231_scan0001_MonitorMD')
ConvertCWPDMDToSpectra(InputWorkspace='HB2A_exp0231_scan0001_DataMD', InputMonitorWorkspace='HB2A_exp0231_scan0001_MonitorMD', BinningParams='5,0.1,150', OutputWorkspace='TTheta_No30_40', NeutronWaveLength=2.4100000000000001, ExcludedDetectorIDs='30,31,32,33,34,35,36,37,38,39,40', LinearInterpolateZeroCounts=False)
ConvertCWPDMDToSpectra(InputWorkspace='HB2A_exp0231_scan0001_DataMD', InputMonitorWorkspace='HB2A_exp0231_scan0001_MonitorMD', BinningParams='5,0.1,150', OutputWorkspace='TTheta_No20_30', NeutronWaveLength=2.4100000000000001, ExcludedDetectorIDs='30-39',
