######################################################################
#Python Script Generated by Algorithm History Display 
######################################################################
LoadRaw(Filename="OFFSPEC00005588.raw",OutputWorkspace="OFFSPEC00005588",LoadLogFiles="0")
ConvertUnits(InputWorkspace="OFFSPEC00005588",OutputWorkspace="5588lambda",Target="Wavelength")
CropWorkspace(InputWorkspace="5588lambda",OutputWorkspace="5588spec113",StartWorkspaceIndex="113",EndWorkspaceIndex="113")
Divide(LHSWorkspace="5588spec113",RHSWorkspace="5588spec113",OutputWorkspace="unitywksp")
ReplaceSpecialValues(InputWorkspace="unitywksp",OutputWorkspace="unitywksp",NaNValue="1",NaNError="1",InfinityValue="1",InfinityError="1")
ws = ConvertUnits(InputWorkspace="unitywksp",OutputWorkspace="unityQ",Target="MomentumTransfer").workspace()
print ws.isDistribution()
Rebin(InputWorkspace="unityQ",OutputWorkspace="test1",Params="0.007,-0.01,5")
#ConvertToDistribution(Workspace="test1")
