######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
LoadFullprofResolution(Filename=r'2013A_HR60b1.irf',OutputWorkspace='PG3_Profile')
SaveFullprofResolution(InputWorkspace='PG3_Profile', OutputFilename='/tmp/test10.irf', Bank=1, ProfileFunction='Jason Hodge\'s function (profile 10)')
