######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
LoadFullprofResolution(Filename=r'HRPD_ISIS_Cycle_10_2.irf',OutputWorkspace='HRPD_Profile')
SaveFullprofResolution(InputWorkspace='HRPD_Profile', 
        OutputFilename='/tmp/test9.irf', Bank=1, 
        ProfileFunction="Back-to-back exponential convoluted with pseudo-voigt (profile 9)", Append=False)
SaveFullprofResolution(InputWorkspace='HRPD_Profile', 
        OutputFilename='/tmp/test9.irf', Bank=2, 
        ProfileFunction="Back-to-back exponential convoluted with pseudo-voigt (profile 9)", Append=True)
SaveFullprofResolution(InputWorkspace='HRPD_Profile', 
        OutputFilename='/tmp/test9.irf', Bank=3, 
        ProfileFunction="Back-to-back exponential convoluted with pseudo-voigt (profile 9)", Append=True)
