######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
CreateMDWorkspace(Dimensions='3',Extents='0,10,0,10,0,10',Names='A,B,C',Units='A,A,A',OutputWorkspace='original')
FakeMDEventData(InputWorkspace='original',UniformParams='10000',PeakParams='10000,2,2,2,1',RandomizeSignal='1')
BinMD(InputWorkspace='original',AlignedDim0='A,0,10,20',AlignedDim1='B,0,10,20',AlignedDim2='C,0,10,20',OutputWorkspace='binned')
MaskMD(Workspace='binned',Dimensions='A,B,C,A,B,C,A,B,C',Extents='0,10,0,1,0,1,0,1,0,10,0,1,0,1,0,1,0,10')
