######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
LoadMD(Filename=r'MDEW_4D.nxs', OutputWorkspace='MDEW_4D')
BinMD(InputWorkspace='MDEW_4D', AlignedDimX='h,-1.5,1.5,100', AlignedDimY='k,-1.5,1.5,100', AlignedDimZ='l,-1.5,1.5,100', AlignedDimT='E,0,3,1', OutputWorkspace='MDEW_4D_Histo')
