######################################################################
#Python Script Generated by GeneratePythonScript Algorithm
######################################################################
Load(Filename='/WISH00016748.raw',OutputWorkspace='WISH00016748')
ConvertToDiffractionMDWorkspace(InputWorkspace='WISH00016748',OutputWorkspace='mdws',OneEventPerBin='0')
FindPeaksMD(InputWorkspace='mdws',MaxPeaks='10',OutputWorkspace='peaks')
IntegratePeaksMD(InputWorkspace='mdws',PeakRadius='0.02',BackgroundInnerRadius='0.024',BackgroundOuterRadius='0.029999999999999999',PeaksWorkspace='peaks',OutputWorkspace='integrated')

